name: imaging_analysis-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
      - readlif
      - scikit-image
      - pandas
      - matplotlib
      - jupyterlab
      - notebook
      - ipykernel
      - ipywidgets
