name: open2CTEST-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pip
  - notebook
  - jupyterlab
  - cooler
  - cooltools
  - bioframe
  - pybigwig
  - numpy
  - pandas
  - pybbi
  - matplotlib
  - seaborn
